### ISSUE TITLE
MD+ not working

### ISSUE THREAD

**Issue by slash0042** [libretro/picodrive#220]
Hi, I tried Mortal Kombat II Arcade Edition with its soundpack, Nintendo Switch platform (Aarch64), the game boots from the CUE file just fine but with no music, I tried both the WAV set and a single bin file. With Doom 32x Resurrection prompts an error code (will post it once I get my Switch).

**Comment by irixxxx** [comment]
I cannot replicate this with retroarch under Ubuntu. Please supply more information:
On which platform is this happening?
What's the cue file looking like?
Which files are in the directory?

**Comment by slash0042** [comment]
Sorry, I figured it is MD+ no being supported on Picodrive, as 32x streamed music hacks uses MD+ implementation and not MSU-MD

**Comment by irixxxx** [comment]
MD+ is ATM not supported, as I don't have the hardware.

**Comment by irixxxx** [comment]
Basic implementation in v2.01. It only does the audio part of the API and nothing else. I'm not going to do other parts of the API until I see any real software actually using it. IMHO the available API documentation is too sparse to allow for a viable blackbox implementation.

Generally, I think using that API is a bad idea in any case, since only a very limited number of people with Mega CD hardware have the means to use this on real hardware. MSU seems to be a much better idea.
