### ISSUE TITLE
SRAM size reports inconsistently

### ISSUE THREAD

**Issue by GregorR** [libretro/picodrive#36]
I'm working on improving Netplay in RetroArch. One of the changes I made is to allow connections late, rather than forcing Netplay to be connecting from the moment you launch RetroArch.

A consequence of this is that Netplay queries the core's sram size (core_get_memory with id = RETRO_MEMORY_SAVE_RAM) after the core has already been executing for a while. With picodrive—and genesis_plus_gx, unfortunately eliminating all Genesis emulators—the reported value is seemingly correct if it's queried before any frames have been simulated, but is 0 if any frames have been simulated.

This was verified by adding the following snippet to Netplay's pre-frame code:

```
   mem_info.id = RETRO_MEMORY_SAVE_RAM;
   core_get_memory(&mem_info);
   fprintf(stderr, "FRAME %u: %lu\n", netplay->self_frame_count, mem_info.size);
```

The output is as follows:

```
FRAME 0: 16384
FRAME 1: 0
FRAME 2: 0
...
```

Is this expected behavior, in which case Netplay should work around it (though I'm not sure what the correct workaround is...), or a bug?

**Comment by twinaphex** [comment]
Hi @GregorR, 

 @ekeeke is the developer of Genesis Plus GX, he might be able to provide some commentary on this and we could maybe seek a solution to our problems.

**Comment by ekeeke** [comment]
Yes, this is expected behavior. 

See this discussion: https://github.com/ekeeke/Genesis-Plus-GX/issues/19

This was initially implemented in Picodrive then later in Genesis Plus GX due to people complaining about empty SRM files, see https://github.com/ekeeke/Genesis-Plus-GX/commit/7f3803b002d26ea0b3240d1c47ca99e57ffe7275

Basically,  first call reports the max supposed SRAM size since it is supposed to be used for loading and next calls (which are supposed to be saving) report the  SRAM size if it was modified, 0 if SRAM was not modified (for games with no SRAM for example).

This was done like this because libretro API do not distinguish between SRAM load and save when getting the memory size. There isn't really other solution besides improving the API since it's impossible to know for sure SRAM size of Mega Drive games until they actually try to write SRAM.

**Comment by GregorR** [comment]
Got it. I shall try to make Netplay cope.
